Fixed render keep alive url

diff --git a/my-website-main/.github/workflows/keep-alive.yml b/my-website-main/.github/workflows/keep-alive.yml
--- a/my-website-main/.github/workflows/keep-alive.yml
+++ b/my-website-main/.github/workflows/keep-alive.yml
@@ -1,28 +1,23 @@
-name: Keep Render Alive
+name: Keep Render alive
 
 on:
-schedule:
-- cron: '*/5 * * * *'
-workflow_dispatch:
+  schedule:
+    - cron: "*/10 * * * *"
 
 jobs:
-ping:
-runs-on: ubuntu-latest
+  ping:
+    runs-on: ubuntu-latest
 
-```
-steps:
-  - name: Ping backend
-    run: |
-      STATUS=$(curl --silent --output /dev/null \
-      --write-out "%{http_code}" \
-      https://my-website-g7nn.onrender.com/api/)
+    steps:
+      - name: Ping backend
+        run: |
+          STATUS=$(curl --silent --output /dev/null \
+          --write-out "%{http_code}" \
+          https://my-website-g7nn.onrender.com)
 
-      echo "Status: $STATUS"
+          echo "Status: $STATUS"
 
-      if [ "$STATUS" != "200" ]; then
-        echo "Failed"
-        exit 1
-      fi
-
-      echo "Backend is alive"
-```
+          if [ "$STATUS" -ne 200 ]; then
+            echo "Failed"
+            exit 1
+          fi
